### ISSUE TITLE
Merge original repository with a living fork

### ISSUE THREAD

**Issue by castamir** [jkuchar/PdfResponse#1]
You can try and check the direct fork from Schmutzka: https://github.com/Schmutzka/PdfResponse or 
my freshly upgraded fork: https://github.com/castamir/PdfResponse. Difference is mainly in additional handy testing methods in Schmutzka's fork on one hand, and additional composer and background & save mode setters and heavily refactored code on the other hand.

**Comment by jkuchar** [comment]
Already done, just forgot to close this. 🙂
