### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by xdobro4** [jkuchar/PdfResponse#16]
Will be nice to have some [sematic versioning](http://semver.org/). Not necessarily "sematic".

Benefits:
- composer cache ❤️ 
- possibility to include specific revision (for instance my last PR #15 is breaking compatibility for nettefw 2.0, cos is using separate parts of nette)

**Comment by jkuchar** [comment]
Definitely 👍

**Comment by jkuchar** [comment]
Yep, this project is using semantic versioning. Currnly in < 1.x mode.
