### ISSUE TITLE
mPDF footer is ignored

### ISSUE THREAD

**Issue by jannovy** [jkuchar/PdfResponse#17]
Adding footer with mPDF API is not working.

$pdf = new PdfResponse($template);
$pdf->getMPDF()->setFooter('my footer');

has no effect in output pdf document

**Comment by jkuchar** [comment]
There is probably something wrong with mPDF. This library is just tiny wrapper over mPDF.

Try to debug mPDF: https://mpdf.github.io/reference/mpdf-variables/debug.html

**Comment by jkuchar** [comment]
related #14

**Comment by jkuchar** [comment]
#14 is already released.
