### ISSUE TITLE
Blank PDF

### ISSUE THREAD

**Issue by jbezdicekk** [jkuchar/PdfResponse#18]
```
$html = $this->gethttpContents($url);
$pdf = new PdfResponse($html);
$pdf->pageFormat = 'A4';
$pdf->documentTitle = "1";
$this->sendResponse($pdf);
```

valid HTML code is stored in $html variable, so this shouldnt be a problem. Unfortunately the result is blank PDF ... any ideas ?

**Comment by jkuchar** [comment]
There is probably something wrong with mPDF. This library is just tiny wrapper over mPDF.

Try to debug mPDF: https://mpdf.github.io/reference/mpdf-variables/debug.html
