### ISSUE TITLE
Support for mPDF7

### ISSUE THREAD

**Issue by rootpd** [jkuchar/PdfResponse#19]
mPDF7 is coming and it's bringing some breaking changes. I'll create a PR which adds a support for mPDF7, but you'll probably have to decide when and how to merge it, because you'll loose support for older versions of mPDF.

note: Using mPDF < 7 with PHP 7.1 is causing notices/warning/errors on the places, which were valid for older PHP versions.

**Comment by jkuchar** [comment]
That is easy, will just release parallel major release. Thanks for contributing.

**Comment by CZechBoY** [comment]
@jkuchar How is it going?

**Comment by jkuchar** [comment]
see #21

**Comment by jkuchar** [comment]
There are two options:
a) send PR with update to mPDF7 for older release branch
b) make PdfResponse [work without SmartObject](https://github.com/jkuchar/PdfResponse/commit/846f29c9ecd812a35e01ebef66239d6e94e88e80#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) (should not be that hard)

**Comment by jkuchar** [comment]
in b) I mean without Object and without SmartObject (completly remove this dependency)

**Comment by jkuchar** [comment]
Done. https://github.com/jkuchar/PdfResponse/releases/tag/v0.5.0 Reopen if I missed something.
