### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by novotnyj** [jkuchar/PdfResponse#8]
There is pack-a7dbe369407fff7c60d2be94a41fdbdc3b00f834.pack file in .git/objects/pack that has 28.6 MB. So you have 28MB repo, while library itself has 12kB.

**Comment by jkuchar** [comment]
Thank you for reporting that. :+1: But, what can I do about that?

**Comment by novotnyj** [comment]
Seems to me that it is caused by usage of mpdf in previous versions. 
Well to be honest I am not really sure what to do about that:) 

Options might be:

* Start new repo with:

```
git fast-export master~5..master | (cd ../newrepo.git && git init . && git fast-import && git checkout)
```

* Treat it like [sensitive data](https://help.github.com/articles/remove-sensitive-data/).

* Or try using [bfg repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/).

**Comment by jkuchar** [comment]
I think this is quite hard to do in this repo. Because this means to delete practically whole project history. (https://github.com/jkuchar/PdfResponse/commits/master) Because there were mPDF updates included in old SVN repo (is wasn't an issue because with SVN you wasn't downloading whole repo every time)

Please try to prepare it offline and I'm going to provide you link that allows you to upload your proposal of new repo. (just ZIP your whole GIT folder)

**Comment by jkuchar** [comment]
...but wait a second it looks like there are only three relevant commits in history
- INIT
- added composer
- fixed Nette 2.2 compatibility

It look like you are bigger GIT-minja than me, please could you try to squash all those commits into few ones (3-10 commits?)

**Comment by novotnyj** [comment]
After reading [this](http://stackoverflow.com/questions/2164581/remove-file-from-git-repository-history) I have managed to shrink fork of repository using:

```
git filter-branch -f --index-filter 'git rm -rf --cached --ignore-unmatch libs/*' --prune-empty --tag-name-filter cat -- --all
rm -rf .git/refs/original/
git reflog expire --all --expire='0 days'
git fsck --full --unreachable
git repack -A -d
git prune
git push origin --force --tags
```

It seems to affect tag last-for-nette-0-9.

**Comment by jkuchar** [comment]
Wow! Great! This looks really well.

But it is definitely going to break old PdfResponse revisions. I'm going to ask on forum, if it is an issue.

Definitely thank you for assisting!

**Comment by jkuchar** [comment]
I do not think that this is an issue anymore, composer installs this as a ZIP package.
